<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MerchantsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('merchants')->insert([
                ["name"=>"Astons","merchant_logo"=>"Picture1.png"],
                ["name"=>"Big Fish Small Fish","merchant_logo"=>"Picture2.png"],
                ["name"=>"Cathay","merchant_logo"=>"Picture3.png"],
                ["name"=>"Collins","merchant_logo"=>"Picture4.png"],
                ["name"=>"Eighteen Chefs","merchant_logo"=>"Picture5.png"],
                ["name"=>"Fish And Co","merchant_logo"=>"Picture6.png"],
                ["name"=>"HomeTeam NS","merchant_logo"=>"Picture7.png"],
                ["name"=>"llaollao ","merchant_logo"=>"Picture8.png"],
                ["name"=>"Pepper Lunch","merchant_logo"=>"Picture9.png"],
                ["name"=>"Pizza Hut","merchant_logo"=>"Picture10.png"],
                ["name"=>"Shaw theatres","merchant_logo"=>"Picture11.png"],
                ["name"=>"Trapped Escape Room","merchant_logo"=>"Picture12.png"],
                ["name"=>"We Cinema","merchant_logo"=>"Picture13.png"],
                ["name"=>"Wing Zone","merchant_logo"=>"Picture14.png"],
                ["name"=>"Monster Curry","merchant_logo"=>"Picture15.png"],
                ["name"=>"Dookki","merchant_logo"=>"Picture16.png"],
                ["name"=>"Play Nation","merchant_logo"=>"Picture17.png"],
                ["name"=>"Old Chang Kee","merchant_logo"=>"Picture18.png"],
                ["name"=>"Tiger Sugar","merchant_logo"=>"Picture19.png"],
                ["name"=>"Pat Bing Soo","merchant_logo"=>"Picture20.png"],
                ["name"=>"Xcape Singapore","merchant_logo"=>"Picture21.png"],
                ["name"=>"Rocku","merchant_logo"=>"Picture22.png"],
                ["name"=>"Jack's Place","merchant_logo"=>"Picture23.png"],
                ["name"=>"Time Zone","merchant_logo"=>"Picture24.png"],
                ["name"=>"So Ramen","merchant_logo"=>"Picture25.png"],
                ["name"=>"Menbaka Fire Ramen Singapore","merchant_logo"=>"Picture26.png"],
                ["name"=>"Carl's Jr","merchant_logo"=>"Picture27.png"],
                ["name"=>"Madly Good","merchant_logo"=>"Picture28.png"],
                ["name"=>"Haagen Dazs","merchant_logo"=>"Picture29.png"],
                ["name"=>"Cafe Amazon Singapore","merchant_logo"=>"Picture30.png"],
                ["name"=>"The Manhatten Fish Market","merchant_logo"=>"Picture31.png"],
                ["name"=>"Stickies","merchant_logo"=>"Picture32.png"],
                ["name"=>"Popeyes","merchant_logo"=>"Picture33.png"],
                ["name"=>"Prata Wala","merchant_logo"=>"Picture34.png"],
                ["name"=>"Li Ho","merchant_logo"=>"Picture35.png"],
                ["name"=>"Cali Singapore","merchant_logo"=>"Picture36.png"],
                ["name"=>"Takagi Ramen","merchant_logo"=>"Picture37.png"],
                ["name"=>"Ice Bar","merchant_logo"=>"Picture38.png"],
                ["name"=>"Jollibee","merchant_logo"=>"Picture39.png"],
                ["name"=>"Pasta Mania","merchant_logo"=>"Picture40.png"],
                ["name"=>"Bober Tea","merchant_logo"=>"Picture41.png"],
                ["name"=>"Crave","merchant_logo"=>"Picture42.png"],
                ["name"=>"Downtown East Wild Wild Wet","merchant_logo"=>"Picture43.png"],
                ["name"=>"Tampopo","merchant_logo"=>"Picture44.png"],
                ["name"=>"Gong Cha","merchant_logo"=>"Picture45.png"],
                ["name"=>"Texas Chicken","merchant_logo"=>"Picture46.png"],
                ["name"=>"Xing Fu Tang","merchant_logo"=>"Picture47.png"],
                ["name"=>"108 Matcha Saro","merchant_logo"=>"Picture48.png"],
                ["name"=>"Golden Village","merchant_logo"=>"Picture49.png"],
                ["name"=>"Hongdae Oppa","merchant_logo"=>"Picture50.png"],
                ["name"=>"Coffee Bean & Tea Leaf","merchant_logo"=>"Picture51.png"],
                ["name"=>"Sarpino Pizza","merchant_logo"=>"Picture52.png"],
                ["name"=>"Senshi Sushi","merchant_logo"=>"Picture53.png"],
                ["name"=>"Starbucks","merchant_logo"=>"Picture54.png"],
                ["name"=>"Milksha","merchant_logo"=>"Picture55.png"],
                ["name"=>"Tsui Wah","merchant_logo"=>"Picture56.png"],
                ["name"=>"KFC","merchant_logo"=>"Picture57.png"],
                ["name"=>"Dominos Pizza","merchant_logo"=>"Picture58.png"],
                ["name"=>"Shake Shake In A Tub","merchant_logo"=>"Picture59.png"],
                ["name"=>"4Fingers","merchant_logo"=>"Picture60.png"],
                ["name"=>"Sentosa","merchant_logo"=>"Picture61.png"],
                ["name"=>"Awfully Chocolate","merchant_logo"=>"Picture62.png"],
                ["name"=>"Famous Amos","merchant_logo"=>"Picture63.png"],
                ["name"=>"Flash Coffee","merchant_logo"=>"Picture64.png"],
                ["name"=>"Yolأ©","merchant_logo"=>"Picture65.png"],
                ["name"=>"Godiva","merchant_logo"=>"Picture66.png"],
                ["name"=>"Walking on Sunshine","merchant_logo"=>"Picture67.png"],
                ["name"=>"Axe Factor","merchant_logo"=>"Picture68.png"],
                ["name"=>"Tam Jai Sam Gor","merchant_logo"=>"Picture69.png"],
                ["name"=>"Macdonalds","merchant_logo"=>"Picture70.png"],
                ["name"=>"The Alley","merchant_logo"=>"Picture71.png"],
                ["name"=>"Jinjja Chicken","merchant_logo"=>"Picture72.png"],
                ["name"=>"The Original Boat Noodles","merchant_logo"=>"Picture73.png"],
                ["name"=>"R&B Tea","merchant_logo"=>"Picture74.png"],
                ["name"=>"Teabrary","merchant_logo"=>"Picture75.png"],
                ["name"=>"Kebabs Factory","merchant_logo"=>"Picture76.png"],
                ["name"=>"Suki-Ya","merchant_logo"=>"Picture77.png"],
                ["name"=>"Artea","merchant_logo"=>"Picture78.png"],
                ["name"=>"Jurong Bird Park","merchant_logo"=>"Picture79.png"],
                ["name"=>"En Sushi","merchant_logo"=>"Picture80.png"],
                ["name"=>"Burger King","merchant_logo"=>"Picture81.png"],
                ["name"=>"Yoshinoya","merchant_logo"=>"Picture82.png"],
                ["name"=>"At Tea","merchant_logo"=>"Picture83.png"],
                ["name"=>"Deli France","merchant_logo"=>"Picture84.png"],
                ["name"=>"Fat Burger","merchant_logo"=>"Picture85.png"],
                ["name"=>"Yang Guo Fu Mala","merchant_logo"=>"Picture86.png"],
                ["name"=>"Phat Fingers","merchant_logo"=>"Picture87.png"],
                ["name"=>"Play Made","merchant_logo"=>"Picture88.png"],
                ["name"=>"Miso Salmon","merchant_logo"=>"Picture89.png"],
                ["name"=>"Tuk Tuk Cha","merchant_logo"=>"Picture90.png"],
                ["name"=>"Long John Silvers","merchant_logo"=>"Picture91.png"],
                ["name"=>"Som Tam","merchant_logo"=>"Picture92.png"],
                ["name"=>"Colourful Day Cafe","merchant_logo"=>"Picture93.png"],
                ["name"=>"Gloria Jeans","merchant_logo"=>"Picture94.png"],
                ["name"=>"BelleVille","merchant_logo"=>"Picture95.png"],
                ["name"=>"Bazuka Yakiniku","merchant_logo"=>"Picture96.png"],
                ["name"=>"Seven Eleven","merchant_logo"=>"Picture97.png"],
                ["name"=>"apple","merchant_logo"=>"Picture98.png"],
                ["name"=>"samsung","merchant_logo"=>"Picture99.png"],
            ]
        );
    }
}
